package com.example.weatherapp.ui.model

import androidx.compose.ui.graphics.Color
import com.example.weatherapp.R
import com.example.weatherapp.ui.model.WeatherCondition.entries

enum class WeatherCondition(
    val weatherCode: Int,
    val stateName: String,
    val dayDrawableId: Int,
    val nightDrawableId: Int,
    val dayShadowColor: Color,
    val nightShadowColor: Color,
) {
    CLEAR_SKY(
        0,
        "Clear Sky",
        R.drawable.day_clear_sky,
        R.drawable.night_clear_sky,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    MAINLY_CLEAR(
        1,
        "Mainly Clear",
        R.drawable.day_mainly_clear,
        R.drawable.night_mainly_clear,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    PARTLY_CLOUDY(
        2,
        "Partly Cloudy",
        R.drawable.day_partly_cloudy,
        R.drawable.night_partly_cloudy,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    OVERCAST(
        3,
        "Overcast",
        R.drawable.day_overcast,
        R.drawable.night_overcast,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    FOG(
        45,
        "Fog",
        R.drawable.day_fog,
        R.drawable.night_fog,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    DEPOSITING_RIME_FOG(
        48,
        "Depositing Rime Fog",
        R.drawable.day_fog,
        R.drawable.night_fog,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    DRIZZLE_LIGHT(
        51,
        "Light Drizzle",
        R.drawable.day_drizzle_light,
        R.drawable.night_drizzle_light,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    DRIZZLE_MODERATE(
        53,
        "Moderate Drizzle",
        R.drawable.day_drizzle_moderate,
        R.drawable.night_drizzle_moderate,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    DRIZZLE_HIGH(
        55,
        "High Drizzle",
        R.drawable.day_drizzle_intensity,
        R.drawable.night_drizzle_intensity,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    FREEZING_DRIZZLE_LIGHT(
        56,
        "Light Freezing Drizzle",
        R.drawable.day_drizzle_light,
        R.drawable.night_drizzle_light,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    FREEZING_DRIZZLE_HIGH(
        57,
        "High Freezing Drizzle",
        R.drawable.day_freezing_drizzle_intensity,
        R.drawable.night_freezing_drizzle_intensity,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    RAIN_LIGHT(
        61,
        "Light Rain",
        R.drawable.day_rain_slight,
        R.drawable.night_rain_slight,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    RAIN_MODERATE(
        63,
        "Moderate Rain",
        R.drawable.day_rain_moderate,
        R.drawable.night_rain_moderate,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    RAIN_HEAVY(
        65,
        "Heavy Rain",
        R.drawable.day_rain_intensity,
        R.drawable.night_rain_intensity,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    FREEZING_RAIN_LIGHT(
        66,
        "Light Freezing Rain",
        R.drawable.day_freezing_loght,
        R.drawable.night_freezing_light,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    FREEZING_RAIN_HIGH(
        67,
        "High Freezing Rain",
        R.drawable.day_freezing_heavy,
        R.drawable.night_freezing_heavy,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    SNOW_LIGHT(
        71,
        "Light Snow",
        R.drawable.day_snow_fall_light,
        R.drawable.night_snow_fall_light,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    SNOW_MODERATE(
        73,
        "Moderate Snow",
        R.drawable.day_snow_fall_moderate,
        R.drawable.night_snow_fall_moderate,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    SNOW_HEAVY(
        75,
        "Heavy Snow",
        R.drawable.day_snow_fall_intensity,
        R.drawable.night_snow_fall_intensity,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    SNOW_GRAINS(
        77,
        "Grains Snow",
        R.drawable.day_snow_grains,
        R.drawable.night_snow_grains,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    RAIN_SHOWER_LIGHT(
        80,
        "Light Rain Shower",
        R.drawable.day_rain_shower_slight,
        R.drawable.night_rain_shower_slight,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    RAIN_SHOWER_MODERATE(
        81,
        "Moderate Rain Shower",
        R.drawable.day_rain_shower_moderate,
        R.drawable.night_rain_shower_moderate,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    RAIN_SHOWER_HEAVY(
        82,
        "Heavy Rain Shower",
        R.drawable.day_rain_shower_violent,
        R.drawable.night_rain_shower_violent,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    SNOW_SHOWER_LIGHT(
        85,
        "Light Snow Shower",
        R.drawable.day_snow_shower_slight,
        R.drawable.night_snow_shower_slight,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    SNOW_SHOWER_HEAVY(
        86,
        "Heavy Snow Shower",
        R.drawable.day_snow_shower_heavy,
        R.drawable.night_snow_shower_heavy,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    THUNDER_STORM(
        95,
        "Thunderstorm",
        R.drawable.day_thunderstrom_slight_or_moderate,
        R.drawable.night_thunderstrom_slight_or_moderate,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    THUNDER_STORM_HAIL_LIGHT(
        96,
        "Thunderstorm with Light Hail",
        R.drawable.day_thunderstrom_with_slight_hail,
        R.drawable.night_thunderstrom_with_slight_hail,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    THUNDER_STORM_HAIL_HEAVY(
        99,
        "Thunderstorm with Heavy Hail",
        R.drawable.day_thunderstrom_with_heavy_hail,
        R.drawable.night_thunderstrom_with_heavy_hail,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    ),
    UNKNOWN_WEATHER_FORECAST(
        -1,
        "Unknown Weather Forecast",
        R.drawable.day_clear_sky,
        R.drawable.night_clear_sky,
        Color(0xFFFFC701),
        Color(0xFF7E2FFF),
    );

    companion object {
        fun getWeatherCondition(code: Int): WeatherCondition {
            return entries.find {
                it.weatherCode == code
            } ?: UNKNOWN_WEATHER_FORECAST
        }
    }
}